potential.c File Reference
contains functions that compute the potential
#include <stdio.h>
*
#include <stdlib.h>
*
#include <float.h>
*
#include <math.h>
*
#include `global.h`
*
#include `octree.h`
*
#include `fields.h`
*
#include `inline.h`
*
Functions
MIC_ATTR double ccPot (int p1, int p2, int mode, double *mindist)
MIC_ATTR void compPot ()
MIC_ATTR void compRPot ()
MIC_ATTR void ccPotGrad (int p1, int p2, int mode)
MIC_ATTR void compPotGrad ()
MIC_ATTR void compRPotGrad ()
Detailed Description
contains functions that compute the potential
Definition in file potential.c.
Function Documentation
MIC_ATTR double ccPot (int p1, int p2, int mode, double * mindist)
This function computes potential for two neighbour cells. mode=0 - computations for two local cells mode=1 - computations for one local and one remote cell
Definition at line 42 of file potential.c.
References cells, csize, cellData::ctype, partData::ctype, cellData::density, h, h2, h3, recvData, sdim, cellData::size, partData::size, x, cellData::x, partData::x, cellData::y, partData::y, uintVector3d::y, cellData::young, partData::young, cellData::z, partData::z, and uintVector3d::z.
{
  double pot;
  double dist=0.0;
  double size;
  double x, y, z;
  double xc;
  double D;
  double poisson = 0.33;
  double young;
  int ctype;
  if (mode == 0 && p1 == p2)
    return 0.0;
  if (mode == 0) {
    x = cells[p1].x;
    y = cells[p1].y;
    z = cells[p1].z;
    size = cells[p1].size;
    young = cells[p1].young;
    ctype = cells[p1].ctype;
  }
  if (mode == 1) {
    x = recvData[p1].x;
    y = recvData[p1].y;
    z = recvData[p1].z;
    size = recvData[p1].size;
    young = recvData[p1].young;
    ctype = recvData[p1].ctype;
  }
  /* compute the distance between two cells */
  if (sdim == 2)
    dist =
      sqrt((x - cells[p2].x) * (x - cells[p2].x) +
           (y - cells[p2].y) * (y - cells[p2].y));
  if (sdim == 3)
    dist =
      sqrt((x - cells[p2].x) * (x - cells[p2].x) +
           (y - cells[p2].y) * (y - cells[p2].y) +
           (z - cells[p2].z) * (z - cells[p2].z));
  if (mindist[0] > dist && ctype!=1 && cells[p2].ctype!=1) {
    mindist[0] = dist;
  }
  if (dist <= h) {
    double r01, r02;
    double area;
    double sc=1.0;
    if (sdim == 2)
      sc = h2;
    if (sdim == 3)
      sc = h3;
    if (mode == 0) {
      cells[p1].density +=
        sc * (cells[p2].size / csize) * sph_kernel(dist);
    }
    if (mode == 1) {
      #pragma omp atomic
      cells[p2].density += sc * (size / csize) * sph_kernel(dist);
    }
    xc = size + cells[p2].size - dist;
    if (xc <= 0.0)
      return 0.0;
    D = 0.75 * ((1.0 - poisson * poisson) / young +
                (1.0 - poisson * poisson / cells[p2].young));
    /* adhesion */
    r01 =
      (size * size - cells[p2].size * cells[p2].size +
       dist * dist) / (2 * dist);
    r02 = dist - r01;
    area =
      M_PI *
      ((size * size * (size - r01) -
        (size * size * size - r01 * r01 * r01) / 3) +
       (cells[p2].size * cells[p2].size * (cells[p2].size - r02) -
        (cells[p2].size * cells[p2].size * cells[p2].size -
         r02 * r02 * r02) / 3));
    /* compute potential */
    pot =
      (2.0 * pow(xc, 5 / 2) / (5.0 * D)) * sqrt((size * cells[p2].size) /
          (size +
           cells[p2].size)) +
      area * 0.1;
    if(ctype==1 && cells[p2].ctype==1) pot = 0.0;
    return pot;
  } else
    return 0.0;
}
MIC_ATTR void ccPotGrad (int p1, int p2, int mode)
This function computes potential gradient for two neighbour cells. mode=0 - computations for local cells mode=1 - computations for remote cells
Definition at line 256 of file potential.c.
References cells, csize, cellData::ctype, partData::ctype, cellData::density, densPotData::density, m, recvData, recvDensPotData, sdim, cellData::size, partData::size, cellData::v, densPotData::v, v, velocity, cellData::x, partData::x, doubleVector3d::x, cellData::y, partData::y, doubleVector3d::y, cellData::z, partData::z, and doubleVector3d::z.
{
  double grad[3];
  /* we assume that cells' mass is always 1.0 */
  double m = 1.0;
  double sc;
  double x1, x2, y1, y2, z1, z2;
  double v, density, size;
  double dist;
  int ctype;
  if (p1 == p2 && mode == 0)
    return;
  if (mode == 0) {
    x1 = cells[p1].x;
    x2 = cells[p2].x;
    y1 = cells[p1].y;
    y2 = cells[p2].y;
    z1 = cells[p1].z;
    z2 = cells[p2].z;
    v = cells[p2].v;
    density = cells[p2].density;
    size = cells[p2].size;
    ctype = cells[p1].ctype;
  }
  if (mode == 1) {
    x1 = recvData[p1].x;
    x2 = cells[p2].x;
    y1 = recvData[p1].y;
    y2 = cells[p2].y;
    z1 = recvData[p1].z;
    z2 = cells[p2].z;
    v = recvDensPotData[p1].v;
    density = recvDensPotData[p1].density;
    size = recvData[p1].size;
    ctype = recvData[p1].ctype;
  }
  if (sdim == 2)
    dist = sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2));
  if (sdim == 3)
    dist = sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2) +
                (z1 - z2) * (z1 - z2));
  grad[0] = 0.0;
  grad[1] = 0.0;
  grad[2] = 0.0;
  /* compute the gradient of SPH kernel function */
  sph_kernel_gradient(p1, p2, grad, mode, dist);
  if (density == 0.0)
    sc = 0.0;
  else {
    m = size / csize;
    sc = (m / density) * v;
  }
  /* update forces */
  if (mode == 0) {
    velocity[p1].x += sc * grad[0];
    velocity[p1].y += sc * grad[1];
    velocity[p1].z += sc * grad[2];
  } else {
    #pragma omp atomic
    velocity[p2].x -= sc * grad[0];
    #pragma omp atomic
    velocity[p2].y -= sc * grad[1];
    #pragma omp atomic
    velocity[p2].z -= sc * grad[2];
  }
}
MIC_ATTR void compPot ()
This function implements tree walk algorithm for each local cell. Function ccPot(..) is called for each pair of neighbours.
Definition at line 152 of file potential.c.
References ccPot(), cells, _octNode::child, _octNode::data, cellData::density, lnc, statisticsData::mindist, nx, octComputeBox(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octLocateRegion(), octree, s, statistics, tnc, and cellData::v.
{
  if(lnc<=1) return;
  #pragma omp parallel
  {
    int p;
    double mindist;
    mindist=nx;
    #pragma omp for schedule(dynamic,64)
    for (p = 0; p < lnc; p++) {
      int64_t cellIdx;
      int newIdx;
      int s;
      int octIndex;
      struct uintVector3d minLocCode,maxLocCode;
      octHeap octh;
      octHeapInit(&octh);
      cells[p].density = 0.0;
      cells[p].v = 0.0;
      octComputeBox(p,&minLocCode,&maxLocCode);
      octIndex=octLocateRegion(minLocCode,maxLocCode);
      for(s=0; s<tnc; s++) {
        int idx;
        idx=octree[octIndex].child[s];
        if(idx!=-1 && octNodeIntersection(idx,minLocCode,maxLocCode))
          octHeapPush(&octh,idx);
      }
      while(octh.count>0) {
        int idx;
        idx=octHeapPop(&octh);
        cellIdx=octree[idx].data;
        if(cellIdx>=0) {
          cells[p].v += ccPot(p,cellIdx,0,&mindist);
        } else {
          for(s=0; s<tnc; s++) {
            newIdx=octree[idx].child[s];
            if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
              octHeapPush(&octh,newIdx);
          }
        }
      }
      octHeapFree(&octh);
    }
    #pragma omp critical
    statistics.mindist=(statistics.mindist>mindist?mindist:
      statistics.mindist);
  }
}
MIC_ATTR void compPotGrad ()
This function implements tree walk algorithm for each local cell to compute potential gradient. Function ccPotGrad(..) is called for each pair of neighbours.
Definition at line 334 of file potential.c.
References ccPotGrad(), _octNode::child, _octNode::data, lnc, octComputeBox(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octLocateRegion(), octree, s, tnc, velocity, doubleVector3d::x, doubleVector3d::y, and doubleVector3d::z.
{
  int p;
  if(lnc<=1) return;
  #pragma omp parallel for schedule(dynamic,64)
  for(p=0; p<lnc; p++) {
    int64_t cellIdx;
    int newIdx;
    int s;
    int octIndex;
    struct uintVector3d minLocCode,maxLocCode;
    octHeap octh;
    octHeapInit(&octh);
    velocity[p].x=0.0;
    velocity[p].y=0.0;
    velocity[p].z=0.0;
    octComputeBox(p,&minLocCode,&maxLocCode);
    octIndex=octLocateRegion(minLocCode,maxLocCode);
    for(s=0; s<tnc; s++) {
      int idx;
      idx=octree[octIndex].child[s];
      if(idx!=-1 && octNodeIntersection(idx,minLocCode,maxLocCode))
        octHeapPush(&octh,idx);
    }
    while(octh.count>0) {
      int idx;
      idx=octHeapPop(&octh);
      cellIdx=octree[idx].data;
      if(cellIdx>=0) {
        ccPotGrad(p,cellIdx,0);
      } else {
        for(s=0; s<tnc; s++) {
          newIdx=octree[idx].child[s];
          if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
            octHeapPush(&octh,newIdx);
        }
      }
    }
    octHeapFree(&octh);
  }
}
MIC_ATTR void compRPot ()
This function implements tree walk algorithm for each remote cell. Function ccPot(..) is called for each pair of neighbours.
Definition at line 209 of file potential.c.
References ccPot(), cells, _octNode::child, _octNode::data, statisticsData::mindist, numImp, nx, octComputeBoxR(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octree, s, statistics, tnc, cellData::v, and v.
{
  int rp;
  if(numImp<=0) return;
  #pragma omp parallel
  {
    double mindist;
    mindist=nx;
    #pragma omp for schedule(dynamic,64)
    for (rp = 0; rp < numImp; rp++) {
      int64_t cellIdx;
      int newIdx;
      int s;
      double v;
      struct uintVector3d minLocCode,maxLocCode;
      octHeap octh;
      octHeapInit(&octh);
      octComputeBoxR(rp,&minLocCode,&maxLocCode);
      octHeapPush(&octh,0);
      while(octh.count>0) {
        int idx;
        idx=octHeapPop(&octh);
        cellIdx=octree[idx].data;
        if(cellIdx>=0) {
          v=ccPot(rp,cellIdx,1,&mindist);
          #pragma omp atomic
          cells[cellIdx].v += v;
        } else {
          for(s=0; s<tnc; s++) {
            newIdx=octree[idx].child[s];
            if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
              octHeapPush(&octh,newIdx);
          }
        }
      }
      octHeapFree(&octh);
    }
    #pragma omp critical
    statistics.mindist=(statistics.mindist>mindist?mindist:
      statistics.mindist);
  }
}
MIC_ATTR void compRPotGrad ()
This function implements tree walk algorithm for each remote cell to compute potential gradient. Function ccPotGrad(..) is called for each pair of neighbours.
Definition at line 384 of file potential.c.
References ccPotGrad(), _octNode::child, _octNode::data, numImp, octComputeBoxR(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octree, s, and tnc.
{
  int rp;
  if(numImp<=0) return;
  #pragma omp parallel for schedule(dynamic,64)
  for (rp = 0; rp < numImp; rp++) {
    int64_t cellIdx;
    int newIdx;
    int s;
    struct uintVector3d minLocCode,maxLocCode;
    octHeap octh;
    octHeapInit(&octh);
    octComputeBoxR(rp,&minLocCode,&maxLocCode);
    octHeapPush(&octh,0);
    while(octh.count>0) {
      int idx;
      idx=octHeapPop(&octh);
      cellIdx=octree[idx].data;
      if(cellIdx>=0) {
        ccPotGrad(rp,cellIdx,1);
      } else {
        for(s=0; s<tnc; s++) {
          newIdx=octree[idx].child[s];
          if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
            octHeapPush(&octh,newIdx);
        }
      }
    }
    octHeapFree(&octh);
  }
}