potential.h File Reference
Functions
MIC_ATTR void compPot ()
MIC_ATTR void compRPot ()
MIC_ATTR void compPotGrad ()
Function Documentation
MIC_ATTR void compPot ()
This function implements tree walk algorithm for each local cell. Function ccPot(..) is called for each pair of neighbours.
Definition at line 152 of file potential.c.
References ccPot(), cells, _octNode::child, _octNode::data, cellData::density, lnc, statisticsData::mindist, nx, octComputeBox(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octLocateRegion(), octree, s, statistics, tnc, and cellData::v.
{
  if(lnc<=1) return;
  #pragma omp parallel
  {
    int p;
    double mindist;
    mindist=nx;
    #pragma omp for schedule(dynamic,64)
    for (p = 0; p < lnc; p++) {
      int64_t cellIdx;
      int newIdx;
      int s;
      int octIndex;
      struct uintVector3d minLocCode,maxLocCode;
      octHeap octh;
      octHeapInit(&octh);
      cells[p].density = 0.0;
      cells[p].v = 0.0;
      octComputeBox(p,&minLocCode,&maxLocCode);
      octIndex=octLocateRegion(minLocCode,maxLocCode);
      for(s=0; s<tnc; s++) {
        int idx;
        idx=octree[octIndex].child[s];
        if(idx!=-1 && octNodeIntersection(idx,minLocCode,maxLocCode))
          octHeapPush(&octh,idx);
      }
      while(octh.count>0) {
        int idx;
        idx=octHeapPop(&octh);
        cellIdx=octree[idx].data;
        if(cellIdx>=0) {
          cells[p].v += ccPot(p,cellIdx,0,&mindist);
        } else {
          for(s=0; s<tnc; s++) {
            newIdx=octree[idx].child[s];
            if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
              octHeapPush(&octh,newIdx);
          }
        }
      }
      octHeapFree(&octh);
    }
    #pragma omp critical
    statistics.mindist=(statistics.mindist>mindist?mindist:
      statistics.mindist);
  }
}
MIC_ATTR void compPotGrad ()
This function implements tree walk algorithm for each local cell to compute potential gradient. Function ccPotGrad(..) is called for each pair of neighbours.
Definition at line 334 of file potential.c.
References ccPotGrad(), _octNode::child, _octNode::data, lnc, octComputeBox(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octLocateRegion(), octree, s, tnc, velocity, doubleVector3d::x, doubleVector3d::y, and doubleVector3d::z.
{
  int p;
  if(lnc<=1) return;
  #pragma omp parallel for schedule(dynamic,64)
  for(p=0; p<lnc; p++) {
    int64_t cellIdx;
    int newIdx;
    int s;
    int octIndex;
    struct uintVector3d minLocCode,maxLocCode;
    octHeap octh;
    octHeapInit(&octh);
    velocity[p].x=0.0;
    velocity[p].y=0.0;
    velocity[p].z=0.0;
    octComputeBox(p,&minLocCode,&maxLocCode);
    octIndex=octLocateRegion(minLocCode,maxLocCode);
    for(s=0; s<tnc; s++) {
      int idx;
      idx=octree[octIndex].child[s];
      if(idx!=-1 && octNodeIntersection(idx,minLocCode,maxLocCode))
        octHeapPush(&octh,idx);
    }
    while(octh.count>0) {
      int idx;
      idx=octHeapPop(&octh);
      cellIdx=octree[idx].data;
      if(cellIdx>=0) {
        ccPotGrad(p,cellIdx,0);
      } else {
        for(s=0; s<tnc; s++) {
          newIdx=octree[idx].child[s];
          if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
            octHeapPush(&octh,newIdx);
        }
      }
    }
    octHeapFree(&octh);
  }
}
MIC_ATTR void compRPot ()
This function implements tree walk algorithm for each remote cell. Function ccPot(..) is called for each pair of neighbours.
Definition at line 209 of file potential.c.
References ccPot(), cells, _octNode::child, _octNode::data, statisticsData::mindist, numImp, nx, octComputeBoxR(), octHeapFree(), octHeapInit(), octHeapPop(), octHeapPush(), octree, s, statistics, tnc, cellData::v, and v.
{
  int rp;
  if(numImp<=0) return;
  #pragma omp parallel
  {
    double mindist;
    mindist=nx;
    #pragma omp for schedule(dynamic,64)
    for (rp = 0; rp < numImp; rp++) {
      int64_t cellIdx;
      int newIdx;
      int s;
      double v;
      struct uintVector3d minLocCode,maxLocCode;
      octHeap octh;
      octHeapInit(&octh);
      octComputeBoxR(rp,&minLocCode,&maxLocCode);
      octHeapPush(&octh,0);
      while(octh.count>0) {
        int idx;
        idx=octHeapPop(&octh);
        cellIdx=octree[idx].data;
        if(cellIdx>=0) {
          v=ccPot(rp,cellIdx,1,&mindist);
          #pragma omp atomic
          cells[cellIdx].v += v;
        } else {
          for(s=0; s<tnc; s++) {
            newIdx=octree[idx].child[s];
            if(newIdx!=-1 && octNodeIntersection(newIdx,minLocCode,maxLocCode))
              octHeapPush(&octh,newIdx);
          }
        }
      }
      octHeapFree(&octh);
    }
    #pragma omp critical
    statistics.mindist=(statistics.mindist>mindist?mindist:
      statistics.mindist);
  }
}